# Generated by Django 5.1.2 on 2025-03-07 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buisness", "0003_business_equipment_owned_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="last_balance",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "$0"),
                    (2500, "$2,500"),
                    (5000, "$5,000"),
                    (7500, "$7,500"),
                    (10000, "$10,000"),
                    (20000, "$20,000"),
                    (30000, "$30,000"),
                    (40000, "$40,000"),
                    (50000, "$50,000"),
                    (60000, "$60,000"),
                    (70000, "$70,000"),
                    (80000, "$80,000"),
                    (90000, "$90,000"),
                    (100000, "$100,000"),
                    (110000, "$110,000"),
                    (120000, "$120,000"),
                    (130000, "$130,000"),
                    (140000, "$140,000"),
                    (150000, "$150,000"),
                    (160000, "$160,000"),
                    (170000, "$170,000"),
                    (180000, "$180,000"),
                ],
                default=0,
                verbose_name="Total value of equipment owned outright",
            ),
        ),
    ]
