# Generated by Django 5.1.2 on 2025-03-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buisness", "0004_business_last_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="secured_loan_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "--Select One--"),
                    ("at_least_5000", "I have at least $5,000 for the program"),
                    (
                        "need_help_raising_5000",
                        "I need help raising the $5,000 minimum",
                    ),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
