# Generated by Django 5.1.2 on 2025-04-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buisness", "0008_alter_client_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_email",
            field=models.EmailField(
                blank=True, default="NONE", max_length=254, null=True
            ),
        ),
    ]
