# Generated by Django 5.1.2 on 2025-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.RemoveField(
            model_name="customerprofile",
            name="account_info",
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountinfo",
            name="signup_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="otherinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Responding", "Responding"),
                    ("Inactive", "Inactive"),
                ],
                default="Inactive",
                max_length=50,
            ),
        ),
    ]
