# Generated by Django 5.1.2 on 2025-04-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("serviceprovider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("service_provider", "Service Provider"),
                ],
                default="client",
                max_length=50,
            ),
        ),
    ]
